config/routes.rb
Rails.application.routes.draw do
scope '(:locale)' do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new

    post 'login' => :create

    delete "logout" =>:destroy
 end

 #devise_for :users

  resources :user1s
  #devise_for :installs
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
  	get :who_bought, on: :member
  end

  root to: 'store#index', as:'store'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end #end locale
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(product_id: product_id)
			current_item.quantity = 1
		end
		current_item	
	end
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	
	belongs_to :cart
	belongs_to :product
	belongs_to :order, optional: true
	def total_price
		product.price * quantity	
	end
end

app/models/order.rb
class Order < ApplicationRecord
	PAYMENT_TYPES = ['Check', 'Credit Card', 'Purchase order']
	validates :name, :email, :address, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	has_many :line_items, dependent: :destroy
	def add_line_items_form_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
class Product < ApplicationRecord
  #attr_accessible :description, :image_url, :price, :title
  has_many :line_items
  has_many :orders, through: :line_items


  
  before_destroy :check_product
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
# 
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end
  private
  #Kiem tra truoc khi xoa product
  def check_product
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :user_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user1.rb
class User1 < ApplicationRecord
after_destroy :not_delete_user_if_user_only
has_secure_password
validates :name, presence: true, uniqueness: true 
def not_delete_user_if_user_only
	if User1.count.zero?
		raise "Can't delete last user"
	end
end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 skip_before_filter :authorize
 #before_action :set_cart, only: [:index]
 def index
  	@total_orders = Order.count
 	@cart = current_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "ABC #{params[:id]}"
      redirect_to store_url, notice: "Invalid cart"
    else
      respond_to do |format|
        format.html 
        format.json { render json: @cart}
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize
  def index
  	if params[:set_locale]
  		redirect_to store_path(locale: params[:set_locale])
  	else
	  	@products = Product.order(:title)
	  	@cart = current_cart
  	end
   end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user1s_helper.rb
module User1sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now%>
We have <%= @total_orders %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class ='<%= controller.controller_name%>'>
  <div id = 'banner'>        
	<%=image_tag("logo.png") %>
	<%= @page_title || t('.title') %>
   <div class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Language<span class="caret" id="select"></span></a>
        <ul class="dropdown-menu">
              <li><%= link_to "English", :locale=>'en'%></li>
              <li><%= link_to "Tieng Viet", :locale=>'vi'%></li>
        </ul>
      </div>
  </div>
  <div id ='colums'>
  	<div id = 'side'>
      <div id="cart">
          <% unless @cart.line_items.empty? %>
            <%= render @cart %>
          <%end%>    
      </div>

  		<ul>
  			<li>
  				<%= link_to t('.Home'), store_url%>
  			</li>
  			<li>
  				<a href=""><%= t('.Question')%></a>
  			</li>
  			<li>
  				<a href=""><%= t('.New')%></a>
  			</li>
  			<li>
  				<a href=""><%= t('.Contact')%></a>
  			</li>
  		</ul>
      <%if session[:user1_id] %>
        <ul>
          <li><%link_to 'Orders', orders_path%></li>
          <li><%link_to 'Products', products_path%></li>
          <li><%link_to 'Users', user1s_path%></li>
          <%= button_to "Log Out", logout_path, method: :delete %>
        </ul>
      <%end%> 
   	</div>
  </div>
  <div class='main'>
   	 <%= yield %>   	
  </div>
</body>
</html>